export const GET_CATEGORIES_LOAD = "GET_CATEGORIES_LOAD"
export const GET_CATEGORIES_SUCESS ="GET_CATEGORIES_SUCESS"
export const GET_CATEGORIES_FAIL ="GET_CATEGORIES_FAIL"
export const GET_CATEGORIES = "GET_CATEGORIES"


export const PUT_CATEGORY_FAIL = " PUT_CATEGORY_FAIL"  
export const PUT_CATEGORY = " PUT_CATEGORY "

export const GET_CATEGORY_FAIL = " GET_CATEGORY_FAIL "
export const GET_CATEGORY_SUCESS = " GET_CATEGORY_SUCESS "
export const GET_CATEGORY_LOAD= " GET_CATEGORY_LOAD "
