/*create*/ 
export const SHOW_ERROR_MESSAGE = "SHOW_ERROR_MESSAGE"
export const SHOW_SUCCESS_MESSAGE= "SHOW_SUCCESS_MESSAGE"
export const PRODUCTS_LOAD= "PRODUCTS_LOAD"
export const PRODUCTS_FAIL= "PRODUCTS_FAIL"
export const CREATE_PRODUCT ="CREATE_PRODUCT"


/*fetch*/
export const GET_PRODUCTS_LOAD = "GET_PRODUCTS_LOAD"
export const GET_PRODUCTS_SUCESS ="GET_PRODUCTS_SUCESS"
export const GET_PRODUCTS_FAIL ="GET_PRODUCTS_FAIL"
export const GET_PRODUCTS = "GET_PRODUCTS"


/*get 1 product*/ 


export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD"
export const GET_PRODUCT_SUCESS = "GET_PRODUCT_SUCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADD_TO_CART = "ADD_TO_CART"